'use strict';

/**
 * Build TLS YAML configuration string for Traefik.
 *
 * Includes a `tls.stores.default.defaultCertificate` section so that Traefik
 * file-provider certificates are placed in a TLS store and actually served
 * to clients.  Without the store definition Traefik loads the certificates
 * but falls back to its own default self-signed certificate.
 *
 * @param {Array<{certFile: string, keyFile: string}>} certificates
 * @returns {string} YAML content for tls.yml
 */
function buildTLSConfig(certificates) {
  if (!certificates || certificates.length === 0) {
    return '';
  }

  const defaultCert = certificates[0];

  return `# Auto-generated by daas-mkcert-controller
# Do not edit manually
tls:
  stores:
    default:
      defaultCertificate:
        certFile: ${defaultCert.certFile}
        keyFile: ${defaultCert.keyFile}
  certificates:
${certificates.map(cert => `    - certFile: ${cert.certFile}
      keyFile: ${cert.keyFile}`).join('\n')}
`;
}

module.exports = { buildTLSConfig };
