'use strict';

const { buildTLSConfig } = require('./buildTLSConfig');

let passed = 0;
let failed = 0;

function assert(condition, message) {
  if (condition) {
    passed++;
    console.log(`  ✓ ${message}`);
  } else {
    failed++;
    console.error(`  ✗ FAIL: ${message}`);
  }
}

console.log('buildTLSConfig() tests');
console.log('');

// --- Empty input ---
console.log('Empty input:');
assert(buildTLSConfig([]) === '', 'empty array returns empty string');
assert(buildTLSConfig(null) === '', 'null returns empty string');
assert(buildTLSConfig(undefined) === '', 'undefined returns empty string');

console.log('');

// --- Single certificate ---
console.log('Single certificate:');
{
  const certs = [
    { certFile: 'certs/foo.localhost.pem', keyFile: 'certs/foo.localhost-key.pem' }
  ];
  const yml = buildTLSConfig(certs);

  assert(yml.includes('tls:'), 'output contains tls: root key');
  assert(yml.includes('stores:'), 'output contains stores section');
  assert(yml.includes('default:'), 'output contains default store');
  assert(yml.includes('defaultCertificate:'), 'output contains defaultCertificate');
  assert(yml.includes('certFile: certs/foo.localhost.pem'), 'default cert certFile matches first certificate');
  assert(yml.includes('keyFile: certs/foo.localhost-key.pem'), 'default cert keyFile matches first certificate');
  assert(yml.includes('certificates:'), 'output contains certificates list');
  assert(yml.includes('- certFile: certs/foo.localhost.pem'), 'certificates list includes the certificate');
}

console.log('');

// --- Multiple certificates ---
console.log('Multiple certificates:');
{
  const certs = [
    { certFile: 'certs/foo.localhost.pem', keyFile: 'certs/foo.localhost-key.pem' },
    { certFile: 'certs/bar.localhost.pem', keyFile: 'certs/bar.localhost-key.pem' },
    { certFile: 'certs/baz.localhost.pem', keyFile: 'certs/baz.localhost-key.pem' }
  ];
  const yml = buildTLSConfig(certs);

  // The default store should use the first certificate
  const storesIdx = yml.indexOf('stores:');
  const certsListIdx = yml.indexOf('certificates:');
  assert(storesIdx < certsListIdx, 'stores section comes before certificates list');

  // Default certificate should be the first one
  const defaultCertIdx = yml.indexOf('defaultCertificate:');
  const defaultCertFile = yml.indexOf('certFile: certs/foo.localhost.pem');
  assert(defaultCertIdx < defaultCertFile, 'defaultCertificate references first certificate');

  // All certificates should be in the list
  assert(yml.includes('- certFile: certs/foo.localhost.pem'), 'certificates list includes first cert');
  assert(yml.includes('- certFile: certs/bar.localhost.pem'), 'certificates list includes second cert');
  assert(yml.includes('- certFile: certs/baz.localhost.pem'), 'certificates list includes third cert');
  assert(yml.includes('keyFile: certs/bar.localhost-key.pem'), 'certificates list includes second cert key');
  assert(yml.includes('keyFile: certs/baz.localhost-key.pem'), 'certificates list includes third cert key');
}

console.log('');

// --- YAML structure validity ---
console.log('YAML structure:');
{
  const certs = [
    { certFile: 'certs/app.localhost.pem', keyFile: 'certs/app.localhost-key.pem' }
  ];
  const yml = buildTLSConfig(certs);
  const lines = yml.split('\n');

  assert(lines[0].startsWith('#'), 'first line is a comment');
  assert(lines[1].startsWith('#'), 'second line is a comment');
  assert(lines[2] === 'tls:', 'third line is tls: root key');
  assert(lines[3] === '  stores:', 'fourth line is stores section (2-space indent)');
  assert(lines[4] === '    default:', 'fifth line is default store (4-space indent)');
  assert(lines[5] === '      defaultCertificate:', 'sixth line is defaultCertificate (6-space indent)');
}

console.log('');

// --- Auto-generated header ---
console.log('Auto-generated header:');
{
  const certs = [
    { certFile: 'certs/x.pem', keyFile: 'certs/x-key.pem' }
  ];
  const yml = buildTLSConfig(certs);
  assert(yml.includes('Auto-generated by daas-mkcert-controller'), 'contains auto-generated header');
  assert(yml.includes('Do not edit manually'), 'contains do-not-edit warning');
}

console.log('');

// --- Summary ---
console.log('---');
console.log(`Results: ${passed} passed, ${failed} failed`);

if (failed > 0) {
  process.exit(1);
}
